name: CI

on: [push, pull_request]

jobs:
  netmiko:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Installer les dépendances Netmiko
      - name: Install dependencies (Netmiko)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_netmiko.txt

      # 4. Vérifier formatage Black
      - name: Run Black
        run: black --check .

      # 5. Vérifier Ruff (lint)
      - name: Run Ruff
        run: ruff check .

      # 6. Lancer les tests Pytest (Netmiko)
      - name: Run Pytest (Netmiko)
        run: pytest -q --disable-warnings tests/netmiko

  napalm:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Installer Python
      - name: Set up Python
       uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Installer les dépendances Napalm
      - name: Install dependencies (Napalm)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_napalm.txt

      # 4. Vérifier formatage Black
      - name: Run Black
        run: black --check .

      # 5. Vérifier Ruff (lint)
      - name: Run Ruff
        run: ruff check .

      # 6. Lancer les tests Pytest (Napalm)
      - name: Run Pytest (Napalm)
        run: pytest -q --disable-warnings tests/napalm
